# Generated by Django 6.0.4 on 2026-04-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_google_sub"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="analysis_xp_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_activity_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="quiz_xp_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_analyses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unique_materials",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="xp_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AnalysisRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("class_id", models.CharField(blank=True, max_length=120)),
                ("item_name", models.CharField(max_length=255)),
                ("material", models.CharField(blank=True, max_length=120)),
                ("disposal_stream", models.CharField(blank=True, max_length=120)),
                ("recommendation", models.TextField(blank=True)),
                ("dropoff", models.TextField(blank=True)),
                ("preparation", models.TextField(blank=True)),
                ("hazardous", models.BooleanField(default=False)),
                ("reusable", models.BooleanField(default=False)),
                ("uncertain_prediction", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=0.0)),
                ("xp_awarded", models.PositiveIntegerField(default=0)),
                ("quiz_questions", models.JSONField(blank=True, default=list)),
                ("quiz_completed", models.BooleanField(default=False)),
                ("quiz_score", models.PositiveSmallIntegerField(default=0)),
                ("quiz_xp_awarded", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="MissionClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mission_key", models.CharField(max_length=80)),
                ("week_start", models.DateField()),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-claimed_at",)},
        ),
        migrations.CreateModel(
            name="XpEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("analysis", "Análise"),
                            ("daily_bonus", "Bônus diário"),
                            ("discovery_bonus", "Descoberta"),
                            ("mission", "Missão"),
                            ("quiz", "Quiz"),
                        ],
                        max_length=40,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=140)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="xp_events",
                        to="accounts.analysisrecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="missionclaim",
            constraint=models.UniqueConstraint(
                fields=("user", "mission_key", "week_start"),
                name="unique_mission_claim_per_week",
            ),
        ),
    ]
