# Generated by Django 6.0.4 on 2026-04-17 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_avatar_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpevent',
            name='source',
            field=models.CharField(choices=[('analysis', 'Análise'), ('daily_bonus', 'Bônus diário'), ('discovery_bonus', 'Descoberta'), ('mission', 'Missão'), ('quiz', 'Quiz'), ('battle', 'Batalha')], max_length=40),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('declined', 'Recusada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('requester', 'addressee'), name='unique_friend_request_direction'), models.CheckConstraint(condition=models.Q(('requester', models.F('addressee')), _negated=True), name='friendship_no_self_request')],
            },
        ),
        migrations.CreateModel(
            name='SustainabilityBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('declined', 'Recusada'), ('completed', 'Concluida'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('title', models.CharField(default='Desafio Verde', max_length=160)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('challenger_answers', models.JSONField(blank=True, default=dict)),
                ('opponent_answers', models.JSONField(blank=True, default=dict)),
                ('challenger_score', models.PositiveSmallIntegerField(default=0)),
                ('opponent_score', models.PositiveSmallIntegerField(default=0)),
                ('challenger_completed_at', models.DateTimeField(blank=True, null=True)),
                ('opponent_completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_battles', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_battles', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('challenger', models.F('opponent')), _negated=True), name='battle_no_self_challenge')],
            },
        ),
    ]
