# Generated by Django 6.0.4 on 2026-04-17 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_xpevent_source_friendship_sustainabilitybattle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabilitybattle',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sustainabilitybattle',
            name='current_phase',
            field=models.CharField(choices=[('primary', 'Resposta principal'), ('steal', 'Resposta de roubo'), ('completed', 'Concluida')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='sustainabilitybattle',
            name='current_turn_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_battles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sustainabilitybattle',
            name='question_cursor',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sustainabilitybattle',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('friend_request', 'Pedido de amizade'), ('friend_accepted', 'Amizade aceita'), ('battle_invite', 'Convite de batalha'), ('battle_accepted', 'Batalha aceita'), ('battle_declined', 'Batalha recusada'), ('battle_turn', 'Seu turno'), ('battle_steal', 'Chance de roubar pontos'), ('battle_completed', 'Batalha concluida')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.sustainabilitybattle')),
                ('friendship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.friendship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
