from django.urls import path
from .views import (
    BattleActionView,
    BattleCreateView,
    BattleDetailView,
    BattleSubmitView,
    ConfirmPasswordResetView,
    FriendRequestActionView,
    FriendRequestCreateView,
    GameOverviewView,
    GoogleAuthView,
    LoginView,
    LogoutView,
    MeView,
    NotificationReadView,
    NotificationsView,
    PublicProfileView,
    RegisterView,
    RequestPasswordResetView,
    ResendVerificationView,
    SocialOverviewView,
    SocialUserSearchView,
    SubmitQuizView,
    UpdateAvatarView,
    UpdateUsernameView,
    VerifyEmailView,
)

urlpatterns = [
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('google/', GoogleAuthView.as_view()),
    path('logout/', LogoutView.as_view()),
    path('me/', MeView.as_view()),
    path('me/avatar/', UpdateAvatarView.as_view()),
    path('me/username/', UpdateUsernameView.as_view()),
    path('verify-email/', VerifyEmailView.as_view()),
    path('resend-verification/', ResendVerificationView.as_view()),
    path('password-reset/request/', RequestPasswordResetView.as_view()),
    path('password-reset/confirm/', ConfirmPasswordResetView.as_view()),
    path('game/overview/', GameOverviewView.as_view()),
    path('game/quiz/', SubmitQuizView.as_view()),
    path('social/overview/', SocialOverviewView.as_view()),
    path('social/notifications/', NotificationsView.as_view()),
    path('social/notifications/read/', NotificationReadView.as_view()),
    path('social/users/', SocialUserSearchView.as_view()),
    path('social/profile/<str:username>/', PublicProfileView.as_view()),
    path('social/friends/request/', FriendRequestCreateView.as_view()),
    path('social/friends/requests/<int:request_id>/', FriendRequestActionView.as_view()),
    path('social/battles/', BattleCreateView.as_view()),
    path('social/battles/<int:battle_id>/', BattleDetailView.as_view()),
    path('social/battles/<int:battle_id>/action/', BattleActionView.as_view()),
    path('social/battles/<int:battle_id>/submit/', BattleSubmitView.as_view()),
]
